### ISSUE TITLE
ChargingPoint possibilities

### ISSUE THREAD

**Issue by goRaspy** [aymen-mouelhi/ocpp-js#2]
Hello,

Is it possible to use your project to emulate a ChargingPoint ? Or it is just for CentralSystem ?
Regards

**Comment by aymen-mouelhi** [comment]
Hi,

It is possible to emulate a charging point (or many). I still didn't update the documentation but here is how you can do this:
````
// Create the server
node test/centralServer.js 

// Create the client(s)
node test/client.js

`````

PS: You can update the code in client.js to perform all the supported calls to the server. the client.js creates 2 clients, you can adapt it for usage :)

Aymen
