### ISSUE TITLE
Hello, I would like to know how to get chargePointClient in CenterSystem? Can you answer it for me?

### ISSUE THREAD

**Issue by mrhu-xiansheng** [aymen-mouelhi/ocpp-js#33]
Hello, I would like to know how to get chargePointClient in CenterSystem? Can you answer it for me?

**Comment by aymen-mouelhi** [comment]
Hello Hu,
I added the method getOnlineChargePoints in the CentralSystem to get the list of the charging points.
Cheers,
Aymen
